[[redirects]]
  from = "https://thecleannetwork.co.uk/*"
  to = "https://www.cleannetwork.co.uk/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.thecleannetwork.co.uk/*"
  to = "https://www.cleannetwork.co.uk/:splat"
  status = 301
  force = true