backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/images/services" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/services" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "services" # Used in routes, e.g., /admin/collections/blog
    label: "Service" # Used in the UI
    folder: "src/content/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "ServiceType", name: "type", widget: "select",  options: ["indoor", "external"]}
      - {label: "CoverImage", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "sectors" # Used in routes, e.g., /admin/collections/blog
    label: "Sector" # Used in the UI
    folder: "src/content/sectors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "CoverImage", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}