backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/media"
public_folder: "/images/media"

collections:
  - name: "services"
    label: "Service"
    folder: "src/content/services" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", pattern: ['^.{0,155}$', "155 characters maximum"], required: false}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", pattern: ['^.{0,350}$', "350 characters maximum"], required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "ServiceType", name: "type", widget: "select",  options: ["indoor", "external"]}
      - {label: "CoverImage", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "sectors"
    label: "Sector"
    folder: "src/content/sectors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", pattern: ['^.{0,155}$', "155 characters maximum"], required: false}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", pattern: ['^.{0,350}$', "350 characters maximum"], required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "CoverImage", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "testimonials"
    label: "Testimonial"
    folder: "src/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Avatar", name: "avatar", widget: "image"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Heading", name: "heading", widget: "text"}
      - {label: "Paragraph01", name: "paragraph01", widget: "text", required: false}
      - {label: "Paragraph02", name: "paragraph02", widget: "text", required: false}
      - {label: "Paragraph03", name: "paragraph03", widget: "text", required: false}
  

  - name: "benefits"
    label: "Benefits"
    folder: "src/content/benefits"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Title", name: "title", widget: "string"}


  - name: "blog"
    label: "Blog Post"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime", format: "MMM DD YYYY"}
      - {label: "Category", name: "category", widget: "select", options: ["cleaning", "health-and-environment", "efficiency"], multiple: false}
      - {label: "HeroImage", name: "heroImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}